version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pillsync-api
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm run start
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - notification-net

  redis:
    image: redis:7-alpine
    container_name: notification-redis
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy noeviction
      --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notification-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: notification-redis-ui
    restart: unless-stopped
    ports:
      - '8082:8081'
    environment:
      REDIS_HOSTS: local:redis:6379:0:${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - notification-net

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - notification-net

volumes:
  redis-data:
  mongo_data:

networks:
  notification-net:
    driver: bridge