services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pillsync-api
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

